---
- name: debian update apt-get repo and cache
  apt: 
    update_cache: yes 
    force_apt_get: yes 
    cache_valid_time: 3600

- name: debian install common package
  apt:
    name:
      - vim
      - cron
      - tree
      - inetutils-ping
      - netcat
      - lsof
      - tcpdump
      - iptables
    state: present

- name: install addition package
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ addition_packages }}"

- name: debian kernel tunning
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - name: net.ipv4.ip_forward
      value: 1
    - name: net.ipv6.conf.all.forwarding
      value: 1