---
- name: copy enabled site file
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/sites-available
    owner: root
    mode: 0644
  with_fileglob:
    - files/*
  notify:
    - restart nginx
  tags:
    - nginx_configure

- name: enable sites
  file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    owner: root
    state: link
  with_items: "{{ enabled_sites }}"
  notify:
    - restart nginx
  tags:
    - nginx_configure

- name: disable sites
  file:
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: absent
  with_items: "{{ disabled_sites }}"
  notify:
    - restart nginx
  tags:
    - nginx_configure