position=top-left
fps
fps_metrics=avg,0.01
frametime
frame_timing
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_power
vram
cpu_stats
cpu_temp
cpu_mhz
cpu_power
ram
engine_version
vulkan_driver
wine
toggle_hud=Shift_R+F12
