---
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_admin_email: linh1612340@gmail.com
certbot_certs:
   - domains:
       - prometheus.farmhub.asia
       - grafana.farmhub.asia
certbot_create_standalone_stop_services:
  - nginx

certbot_create_command: >-
  certbot --nginx --noninteractive --agree-tos
  --email {{ cert_item.email | default(certbot_admin_email) }}
  -d {{ cert_item.domains | join(',') }}
  {{ '--pre-hook /etc/letsencrypt/renewal-hooks/pre/stop_services'
    if certbot_create_standalone_stop_services
  else '' }}
  {{ '--post-hook /etc/letsencrypt/renewal-hooks/post/start_services'
    if certbot_create_standalone_stop_services
  else '' }}